/*
  File: embedding_defaults.go
  Purpose: Provide default embedding model catalog entries.
  Author: CodeTextor project
*/

package models

// DefaultEmbeddingModels returns a curated catalog of models that ship with CodeTextor.
// These entries populate the global embedding model table the first time the app runs.
func DefaultEmbeddingModels() []*EmbeddingModelInfo {
	return []*EmbeddingModelInfo{
		{
			ID:                  "fastembed/bge-small-en-v1.5",
			DisplayName:         "FastEmbed · BGE Small",
			Backend:             "fastembed",
			Description:         "CPU-friendly 384-dim English encoder powered by fastembed.",
			Dimension:           384,
			DiskSizeBytes:       80 * 1024 * 1024,
			RAMRequirementBytes: 256 * 1024 * 1024,
			CPULatencyMs:        15,
			IsMultilingual:      false,
			CodeQuality:         "good",
			Notes:               "No external runtime required; ideal default choice.",
			SourceType:          "fastembed",
			CodeFocus:           "general",
			MaxSequenceLength:   512,
			DownloadStatus:      "pending",
		},
		{
			ID:                  "fastembed/gte-small",
			DisplayName:         "FastEmbed · GTE Small",
			Backend:             "fastembed",
			Description:         "Lightweight 384-dim multilingual encoder tuned for natural-language queries.",
			Dimension:           384,
			DiskSizeBytes:       90 * 1024 * 1024,
			RAMRequirementBytes: 300 * 1024 * 1024,
			CPULatencyMs:        18,
			IsMultilingual:      true,
			CodeQuality:         "fair",
			Notes:               "Works out-of-the-box via fastembed.",
			SourceType:          "fastembed",
			CodeFocus:           "general",
			MaxSequenceLength:   512,
			DownloadStatus:      "pending",
		},
		{
			ID:                  "baai/bge-small-en-v1.5",
			DisplayName:         "BGE Small EN v1.5",
			Backend:             "onnx",
			Description:         "Fast CPU-friendly English general-purpose retriever (384 dims).",
			Dimension:           384,
			DiskSizeBytes:       130 * 1024 * 1024, // ~130 MB
			RAMRequirementBytes: 512 * 1024 * 1024, // ~0.5 GB
			CPULatencyMs:        25,
			IsMultilingual:      false,
			CodeQuality:         "good",
			Notes:               "Requires ONNX Runtime.",
			SourceType:          "onnx",
			SourceURI:           "https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/onnx/model.onnx?download=1",
			TokenizerURI:        "https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer.json?download=1",
			PreferredFilename:   "model.onnx",
			MaxSequenceLength:   512,
			License:             "Apache-2.0",
			DownloadStatus:      "pending",
			CodeFocus:           "general",
		},
		{
			ID:                  "ibm-granite/granite-embedding-107m-multilingual",
			DisplayName:         "Granite 107M Multilingual",
			Backend:             "onnx",
			Description:         "IBM Granite multilingual embedding model (768 dims).",
			Dimension:           768,
			DiskSizeBytes:       400 * 1024 * 1024, // ~400 MB
			RAMRequirementBytes: 800 * 1024 * 1024, // ~0.8 GB
			CPULatencyMs:        35,
			IsMultilingual:      true,
			CodeQuality:         "fair",
			Notes:               "Requires ONNX Runtime.",
			SourceType:          "onnx",
			SourceURI:           "https://huggingface.co/ibm-granite/granite-embedding-107m-multilingual/resolve/main/model.onnx?download=1",
			TokenizerURI:        "https://huggingface.co/ibm-granite/granite-embedding-107m-multilingual/resolve/main/tokenizer.json?download=1",
			PreferredFilename:   "model.onnx",
			MaxSequenceLength:   512,
			License:             "Apache-2.0",
			DownloadStatus:      "pending",
			CodeFocus:           "general",
		},
		{
			ID:                  "baai/bge-base-en-v1.5",
			DisplayName:         "BGE Base EN v1.5",
			Backend:             "onnx",
			Description:         "Reliable 768-dim encoder tuned for English retrieval.",
			Dimension:           768,
			DiskSizeBytes:       420 * 1024 * 1024,
			RAMRequirementBytes: 900 * 1024 * 1024,
			CPULatencyMs:        40,
			IsMultilingual:      false,
			CodeQuality:         "great",
			Notes:               "Requires ONNX Runtime.",
			SourceType:          "onnx",
			SourceURI:           "https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/onnx/model.onnx?download=1",
			TokenizerURI:        "https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/tokenizer.json?download=1",
			PreferredFilename:   "model.onnx",
			MaxSequenceLength:   512,
			License:             "MIT",
			DownloadStatus:      "pending",
			CodeFocus:           "general",
		},
		{
			ID:                  "baai/bge-large-en-v1.5",
			DisplayName:         "BGE Large EN v1.5",
			Backend:             "onnx",
			Description:         "Top-quality 1024-dim encoder for maximum precision (English only).",
			Dimension:           1024,
			DiskSizeBytes:       1300 * 1024 * 1024,
			RAMRequirementBytes: 2200 * 1024 * 1024,
			CPULatencyMs:        85,
			IsMultilingual:      false,
			CodeQuality:         "excellent",
			Notes:               "Requires ONNX Runtime.",
			SourceType:          "onnx",
			SourceURI:           "https://huggingface.co/BAAI/bge-large-en-v1.5/resolve/main/onnx/model.onnx?download=1",
			TokenizerURI:        "https://huggingface.co/BAAI/bge-large-en-v1.5/resolve/main/tokenizer.json?download=1",
			PreferredFilename:   "model.onnx",
			MaxSequenceLength:   512,
			License:             "MIT",
			DownloadStatus:      "pending",
			CodeFocus:           "general",
		},
		{
			ID:                  "intfloat/e5-base-v2",
			DisplayName:         "E5 Base v2",
			Backend:             "onnx",
			Description:         "Balanced 768-dim encoder for NL queries and lightweight code search.",
			Dimension:           768,
			DiskSizeBytes:       420 * 1024 * 1024,
			RAMRequirementBytes: 900 * 1024 * 1024,
			CPULatencyMs:        40,
			IsMultilingual:      false,
			CodeQuality:         "great",
			Notes:               "Requires ONNX Runtime.",
			SourceType:          "onnx",
			SourceURI:           "https://huggingface.co/intfloat/e5-base-v2/resolve/main/onnx/model.onnx?download=1",
			TokenizerURI:        "https://huggingface.co/intfloat/e5-base-v2/resolve/main/onnx/tokenizer.json?download=1",
			PreferredFilename:   "model.onnx",
			MaxSequenceLength:   512,
			License:             "Apache-2.0",
			DownloadStatus:      "pending",
			CodeFocus:           "general",
		},
		{
			ID:                  "intfloat/e5-large-v2",
			DisplayName:         "E5 Large v2",
			Backend:             "onnx",
			Description:         "1024-dim variant with higher recall and heavier footprint.",
			Dimension:           1024,
			DiskSizeBytes:       1000 * 1024 * 1024,
			RAMRequirementBytes: 1800 * 1024 * 1024,
			CPULatencyMs:        70,
			IsMultilingual:      false,
			CodeQuality:         "great",
			Notes:               "Requires ONNX Runtime.",
			SourceType:          "onnx",
			SourceURI:           "https://huggingface.co/intfloat/e5-large-v2/resolve/main/onnx/model.onnx?download=1",
			TokenizerURI:        "https://huggingface.co/intfloat/e5-large-v2/resolve/main/tokenizer.json?download=1",
			PreferredFilename:   "model.onnx",
			MaxSequenceLength:   512,
			License:             "Apache-2.0",
			DownloadStatus:      "pending",
			CodeFocus:           "general",
		},
		{
			ID:                  "intfloat/multilingual-e5-base",
			DisplayName:         "E5 Base Multilingual",
			Backend:             "onnx",
			Description:         "Reliable 768-dim multilingual encoder for docs + code.",
			Dimension:           768,
			DiskSizeBytes:       420 * 1024 * 1024,
			RAMRequirementBytes: 900 * 1024 * 1024,
			CPULatencyMs:        45,
			IsMultilingual:      true,
			CodeQuality:         "good",
			Notes:               "Requires ONNX Runtime.",
			SourceType:          "onnx",
			SourceURI:           "https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/onnx/model.onnx?download=1",
			TokenizerURI:        "https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/onnx/tokenizer.json?download=1",
			PreferredFilename:   "model.onnx",
			MaxSequenceLength:   512,
			License:             "Apache-2.0",
			DownloadStatus:      "pending",
			CodeFocus:           "general",
		},
		{
			ID:                  "intfloat/multilingual-e5-large",
			DisplayName:         "E5 Large Multilingual",
			Backend:             "onnx",
			Description:         "1024-dim multilingual encoder with excellent recall.",
			Dimension:           1024,
			DiskSizeBytes:       1000 * 1024 * 1024,
			RAMRequirementBytes: 1800 * 1024 * 1024,
			CPULatencyMs:        75,
			IsMultilingual:      true,
			CodeQuality:         "great",
			Notes:               "Requires ONNX Runtime.",
			SourceType:          "onnx",
			SourceURI:           "https://huggingface.co/intfloat/multilingual-e5-large/resolve/main/onnx/model.onnx?download=1",
			TokenizerURI:        "https://huggingface.co/intfloat/multilingual-e5-large/resolve/main/onnx/tokenizer.json?download=1",
			PreferredFilename:   "model.onnx",
			MaxSequenceLength:   512,
			License:             "Apache-2.0",
			DownloadStatus:      "pending",
			CodeFocus:           "general",
		},
		{
			ID:                  "nomic-ai/nomic-embed-text-v1.5",
			DisplayName:         "Nomic Embed Text v1.5",
			Backend:             "onnx",
			Description:         "Balanced 768-dim encoder for docs + code.",
			Dimension:           768,
			DiskSizeBytes:       330 * 1024 * 1024,
			RAMRequirementBytes: 800 * 1024 * 1024,
			CPULatencyMs:        35,
			IsMultilingual:      false,
			CodeQuality:         "good",
			Notes:               "Requires ONNX Runtime.",
			SourceType:          "onnx",
			SourceURI:           "https://huggingface.co/nomic-ai/nomic-embed-text-v1.5/resolve/main/model.onnx?download=1",
			TokenizerURI:        "https://huggingface.co/nomic-ai/nomic-embed-text-v1.5/resolve/main/tokenizer.json?download=1",
			PreferredFilename:   "model.onnx",
			MaxSequenceLength:   512,
			License:             "Apache-2.0",
			DownloadStatus:      "pending",
			CodeFocus:           "general",
		},
		{
			ID:                  "nomic-ai/nomic-embed-code",
			DisplayName:         "Nomic Embed Code",
			Backend:             "onnx",
			Description:         "1024-dim encoder specialized for source code.",
			Dimension:           1024,
			DiskSizeBytes:       500 * 1024 * 1024,
			RAMRequirementBytes: 1200 * 1024 * 1024,
			CPULatencyMs:        40,
			IsMultilingual:      false,
			CodeQuality:         "great",
			Notes:               "Requires ONNX Runtime. No official ONNX export is published—set the SourceURI/tokenizer manually if you have a conversion.",
			SourceType:          "onnx",
			SourceURI:           "",
			TokenizerURI:        "",
			PreferredFilename:   "model.onnx",
			MaxSequenceLength:   512,
			License:             "Apache-2.0",
			DownloadStatus:      "pending",
			CodeFocus:           "code",
		},
		{
			ID:                  "sentence-transformers/paraphrase-multilingual-mpnet-base-v2",
			DisplayName:         "Paraphrase Multilingual MPNet",
			Backend:             "onnx",
			Description:         "Popular 768-dim multilingual encoder for international teams.",
			Dimension:           768,
			DiskSizeBytes:       420 * 1024 * 1024,
			RAMRequirementBytes: 900 * 1024 * 1024,
			CPULatencyMs:        45,
			IsMultilingual:      true,
			CodeQuality:         "good",
			Notes:               "Requires ONNX Runtime.",
			SourceType:          "onnx",
			SourceURI:           "https://huggingface.co/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/resolve/main/model.onnx?download=1",
			TokenizerURI:        "https://huggingface.co/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/resolve/main/tokenizer.json?download=1",
			PreferredFilename:   "model.onnx",
			MaxSequenceLength:   512,
			License:             "Apache-2.0",
			DownloadStatus:      "pending",
			CodeFocus:           "general",
		},
		{
			ID:                  "sentence-transformers/all-MiniLM-L6-v2",
			DisplayName:         "all-MiniLM-L6-v2",
			Backend:             "onnx",
			Description:         "Ultra-lightweight 384-dim model for minimal latency.",
			Dimension:           384,
			DiskSizeBytes:       80 * 1024 * 1024,
			RAMRequirementBytes: 400 * 1024 * 1024,
			CPULatencyMs:        20,
			IsMultilingual:      false,
			CodeQuality:         "good",
			Notes:               "Requires ONNX Runtime.",
			SourceType:          "onnx",
			SourceURI:           "https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/model.onnx?download=1",
			TokenizerURI:        "https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer.json?download=1",
			PreferredFilename:   "model.onnx",
			MaxSequenceLength:   512,
			License:             "Apache-2.0",
			DownloadStatus:      "pending",
			CodeFocus:           "general",
		},
	}
}
