// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ClearSelectedProject():Promise<void>;

export function CreateProject(arg1:string,arg2:string):Promise<models.Project>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetProject(arg1:string):Promise<models.Project>;

export function GetSelectedProject():Promise<models.Project>;

export function Greet(arg1:string):Promise<string>;

export function ListProjects():Promise<Array<models.Project>>;

export function ProjectExists(arg1:string):Promise<boolean>;

export function SetSelectedProject(arg1:string):Promise<void>;

export function UpdateProject(arg1:string,arg2:string,arg3:string):Promise<models.Project>;

export function UpdateProjectConfig(arg1:string,arg2:models.ProjectConfig):Promise<models.Project>;
