// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSelectedProject() {
  return window['go']['main']['App']['ClearSelectedProject']();
}

export function CreateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3, arg4);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetFileOutline(arg1, arg2) {
  return window['go']['main']['App']['GetFileOutline'](arg1, arg2);
}

export function GetFilePreviews(arg1, arg2) {
  return window['go']['main']['App']['GetFilePreviews'](arg1, arg2);
}

export function GetGitignorePatterns(arg1) {
  return window['go']['main']['App']['GetGitignorePatterns'](arg1);
}

export function GetIndexingProgress(arg1) {
  return window['go']['main']['App']['GetIndexingProgress'](arg1);
}

export function GetOutlineTimestamps(arg1) {
  return window['go']['main']['App']['GetOutlineTimestamps'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetSelectedProject() {
  return window['go']['main']['App']['GetSelectedProject']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ProjectExists(arg1) {
  return window['go']['main']['App']['ProjectExists'](arg1);
}

export function ReadFileContent(arg1, arg2) {
  return window['go']['main']['App']['ReadFileContent'](arg1, arg2);
}

export function SelectDirectory(arg1, arg2) {
  return window['go']['main']['App']['SelectDirectory'](arg1, arg2);
}

export function SetProjectIndexing(arg1, arg2) {
  return window['go']['main']['App']['SetProjectIndexing'](arg1, arg2);
}

export function SetSelectedProject(arg1) {
  return window['go']['main']['App']['SetSelectedProject'](arg1);
}

export function StartIndexing(arg1) {
  return window['go']['main']['App']['StartIndexing'](arg1);
}

export function StopIndexing(arg1) {
  return window['go']['main']['App']['StopIndexing'](arg1);
}

export function UpdateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3);
}

export function UpdateProjectConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectConfig'](arg1, arg2);
}
