// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSelectedProject() {
  return window['go']['main']['App']['ClearSelectedProject']();
}

export function CreateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3, arg4);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DownloadEmbeddingModel(arg1) {
  return window['go']['main']['App']['DownloadEmbeddingModel'](arg1);
}

export function GetAllProjectsStats() {
  return window['go']['main']['App']['GetAllProjectsStats']();
}

export function GetEmbeddingCapabilities() {
  return window['go']['main']['App']['GetEmbeddingCapabilities']();
}

export function GetFileChunks(arg1, arg2) {
  return window['go']['main']['App']['GetFileChunks'](arg1, arg2);
}

export function GetFileOutline(arg1, arg2) {
  return window['go']['main']['App']['GetFileOutline'](arg1, arg2);
}

export function GetFilePreviews(arg1, arg2) {
  return window['go']['main']['App']['GetFilePreviews'](arg1, arg2);
}

export function GetGitignorePatterns(arg1) {
  return window['go']['main']['App']['GetGitignorePatterns'](arg1);
}

export function GetIndexingProgress(arg1) {
  return window['go']['main']['App']['GetIndexingProgress'](arg1);
}

export function GetMCPConfig() {
  return window['go']['main']['App']['GetMCPConfig']();
}

export function GetMCPStatus() {
  return window['go']['main']['App']['GetMCPStatus']();
}

export function GetMCPTools() {
  return window['go']['main']['App']['GetMCPTools']();
}

export function GetONNXRuntimeSettings() {
  return window['go']['main']['App']['GetONNXRuntimeSettings']();
}

export function GetOutlineTimestamps(arg1) {
  return window['go']['main']['App']['GetOutlineTimestamps'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjectStats(arg1) {
  return window['go']['main']['App']['GetProjectStats'](arg1);
}

export function GetSelectedProject() {
  return window['go']['main']['App']['GetSelectedProject']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListEmbeddingModels() {
  return window['go']['main']['App']['ListEmbeddingModels']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ProjectExists(arg1) {
  return window['go']['main']['App']['ProjectExists'](arg1);
}

export function ReadFileContent(arg1, arg2) {
  return window['go']['main']['App']['ReadFileContent'](arg1, arg2);
}

export function ReindexProject(arg1) {
  return window['go']['main']['App']['ReindexProject'](arg1);
}

export function ResetProjectIndex(arg1) {
  return window['go']['main']['App']['ResetProjectIndex'](arg1);
}

export function SaveEmbeddingModel(arg1) {
  return window['go']['main']['App']['SaveEmbeddingModel'](arg1);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3);
}

export function SelectDirectory(arg1, arg2) {
  return window['go']['main']['App']['SelectDirectory'](arg1, arg2);
}

export function SelectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2, arg3);
}

export function SetProjectIndexing(arg1, arg2) {
  return window['go']['main']['App']['SetProjectIndexing'](arg1, arg2);
}

export function SetSelectedProject(arg1) {
  return window['go']['main']['App']['SetSelectedProject'](arg1);
}

export function StartIndexing(arg1) {
  return window['go']['main']['App']['StartIndexing'](arg1);
}

export function StartMCPServer() {
  return window['go']['main']['App']['StartMCPServer']();
}

export function StopIndexing(arg1) {
  return window['go']['main']['App']['StopIndexing'](arg1);
}

export function StopMCPServer() {
  return window['go']['main']['App']['StopMCPServer']();
}

export function TestONNXRuntimePath(arg1) {
  return window['go']['main']['App']['TestONNXRuntimePath'](arg1);
}

export function ToggleMCPTool(arg1) {
  return window['go']['main']['App']['ToggleMCPTool'](arg1);
}

export function UpdateMCPConfig(arg1) {
  return window['go']['main']['App']['UpdateMCPConfig'](arg1);
}

export function UpdateONNXRuntimeSettings(arg1) {
  return window['go']['main']['App']['UpdateONNXRuntimeSettings'](arg1);
}

export function UpdateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3);
}

export function UpdateProjectConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectConfig'](arg1, arg2);
}
