// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ClearSelectedProject():Promise<void>;

export function CreateProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Project>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetAllProjectsStats():Promise<models.ProjectStats>;

export function GetFileChunks(arg1:string,arg2:string):Promise<Array<models.Chunk>>;

export function GetFileOutline(arg1:string,arg2:string):Promise<Array<models.OutlineNode>>;

export function GetFilePreviews(arg1:string,arg2:models.ProjectConfig):Promise<Array<models.FilePreview>>;

export function GetGitignorePatterns(arg1:string):Promise<Array<string>>;

export function GetIndexingProgress(arg1:string):Promise<models.IndexingProgress>;

export function GetOutlineTimestamps(arg1:string):Promise<Record<string, number>>;

export function GetProject(arg1:string):Promise<models.Project>;

export function GetProjectStats(arg1:string):Promise<models.ProjectStats>;

export function GetSelectedProject():Promise<models.Project>;

export function Greet(arg1:string):Promise<string>;

export function ListProjects():Promise<Array<models.Project>>;

export function ProjectExists(arg1:string):Promise<boolean>;

export function ReadFileContent(arg1:string,arg2:string):Promise<string>;

export function ReindexProject(arg1:string):Promise<void>;

export function ResetProjectIndex(arg1:string):Promise<void>;

export function SelectDirectory(arg1:string,arg2:string):Promise<string>;

export function SetProjectIndexing(arg1:string,arg2:boolean):Promise<void>;

export function SetSelectedProject(arg1:string):Promise<void>;

export function StartIndexing(arg1:string):Promise<void>;

export function StopIndexing(arg1:string):Promise<void>;

export function UpdateProject(arg1:string,arg2:string,arg3:string):Promise<models.Project>;

export function UpdateProjectConfig(arg1:string,arg2:models.ProjectConfig):Promise<models.Project>;
